# Generated by Django 3.2.5 on 2021-07-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_hospital',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
    ]
