# Generated by Django 3.2.5 on 2021-07-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210729_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentdate',
            new_name='appointment_date',
        ),
    ]
