# Generated by Django 3.2.5 on 2021-07-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_doctor_has_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
        ),
    ]
